spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost:3306/meclass?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: hzy
    password: huangziyi.1970
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zy.meclass.entity

#自定义配置-路径
video:
  path: /Users/ziyihuang/Movies

server:
  port: 8080