spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meclass?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: ZYsky131499
    driver-class-name: com.mysql.cj.jdbc.Driver


server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zy.meclass.entity

#自定义配置-路径
video:
  path: /Users/zhangye/Documents/video