# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI

on:
  repository_dispatch:
    types: [ updated ]
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Set up Node.js
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 13.2
    
    - name: Build FE
      run: |
        git clone https://github.com/MrThanlon/meclass-fe.git
        cd meclass-fe
        npm install
        npm run build
        mkdir ../meclass/src/main/resources/public
        cp -r dist/* ../meclass/src/main/resources/public/
        
        
    - name: Build with Maven
      env:
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      run: |
        cd meclass
        envsubst < src/main/resources/application-release.yml > src/main/resources/application.yml
        mvn clean package

    - name: Deploy
      env:
        DEPLOY_SECRET: ${{ secrets.DEPLOY_SECRET }}
      run: |
        echo "$DEPLOY_SECRET" > ~/id_rsa
        chmod 0400 ~/id_rsa
        scp -o "StrictHostKeyChecking no" -i ~/id_rsa meclass/target/*.war root@47.103.204.9:/var/lib/tomcat9/webapps/
        rm ~/id_rsa
